### ISSUE TITLE
Can you add support for a compiler not supported by meson?

### ISSUE THREAD

**Issue by Curculigo** [muon-build/muon#62]
This is the list of compiler ids supported by meson:

https://mesonbuild.com/Reference-tables.html#compiler-ids

Can you add support for a compiler not in this list?

**Comment by eli-schwartz** [comment]
I see no reason why not. Which compiler were you interested in?

**Comment by Curculigo** [comment]
> I see no reason why not. Which compiler were you interested in?

Pelles C and maybe Orange C.
